ECC 667
hmrc/xi-eori-common-component-frontend pull request #17
Opened 2021-11-08 12:28 UTC by vigneshwaripandi

2021-11-08 16:37 UTC, yasaracar requested changes

2021-11-08 16:37 UTC, yasaracar commented on conf/messages
> +sicCode.details.link=<a href="https://www.gov.uk/get-information-about-a-company"class="govuk-link" target="_blank" rel="noopener noreferrer">Find your SIC code (opens in new window or tab)</a>.
Can we do this without adding html to the messages file?
Adding html in a messages file is not a good practice, for example, this file will be sent to Welsh translation team and they will be confused with the html

2021-11-08 16:37 UTC, yasaracar commented on conf/messages
> +sicCode.details.desc=If you do not have one, you can search for a relevant SIC code on <a href="https://resources.companieshouse.gov.uk/sic/" class="govuk-link" target="_blank" rel="noopener noreferr
same here for html

2021-11-08 16:37 UTC, yasaracar commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/controllers/DisclosePersonalDetailsController.scala
> -  private def destinationsByAnswer(disclosePersonalDetails: DisclosePersonalDetails): Result =
Why do we remove this method, it looks like it'd simplify the code a bit

2021-11-08 16:37 UTC, yasaracar commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/forms/SicCodeFormProvider.scala
> +  protected def validSicCode: Constraint[String] =
Do we have unit tests for the forms? I think they should be tested in unit tests as there are a lot of error combinations

2021-11-08 16:37 UTC, yasaracar commented on test/controllers/DisclosePersonalDetailsControllerSpec.scala
> +        ).get shouldBe uk.gov.hmrc.xieoricommoncomponentfrontend.controllers.routes.SicCodeController.onPageLoad().url
Can we add tests for the other scenario where the affinity group is not organisation and the user is redirected to XiEoriNotNeededController.eoriNotNeeded()?

2021-11-08 16:37 UTC, yasaracar commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/controllers/DisclosePersonalDetailsController.scala
> +          if (loggedInUser.affinityGroup.get equals AffinityGroup.Organisation)
it is not good practice to use .get on options, better using something like 
`loggedInUser.affinityGroup match{
case Some(AffinityGroup.Organisation) => ...
case _ => ...
}`

2021-11-09 14:57 UTC, vigneshwaripandi commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/forms/SicCodeFormProvider.scala
> +  protected def validSicCode: Constraint[String] =
I have already added unit tests for the error combinations in the View spec.

2021-11-09 16:42 UTC, yasaracar commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/forms/SicCodeFormProvider.scala
> +  protected def validSicCode: Constraint[String] =
It might be better to test these directly in form test, not in the views. But it is ok for now, I think it needs wider discussion.
Looking at the view tests, there are a few test scenarios missing here, like:
- When there are a few spaces (covers the trim)
- When the length is less than 4
Can you add those tests please?

2021-11-10 08:47 UTC, yasaracar approved these changes

2021-11-10 10:57 UTC, merged