Ecc 679
hmrc/xi-eori-common-component-frontend pull request #18
Opened 2021-11-08 12:30 UTC by NandanaRaghu

2021-11-09 16:26 UTC, yasaracar requested changes

2021-11-09 16:26 UTC, yasaracar commented on test/config/ErrorHandlerSpec.scala
> +        "Redirect to the notfound page on 404 error with InvalidPathParameter" in {
Commented out code

2021-11-10 09:05 UTC, NandanaRaghu commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/config/ErrorHandler.scala
> +        // $COVERAGE-OFF$Loggers
removed coverage statement

2021-11-10 09:06 UTC, NandanaRaghu commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/controllers/ConfirmDetailsController.scala
> +                        ConfirmDetailsViewModel(response, loggedInUser.affinityGroup.get)
fixed the code and removed get

2021-11-10 09:06 UTC, NandanaRaghu commented on test/config/ErrorHandlerSpec.scala
> +        "Redirect to the notfound page on 404 error with InvalidPathParameter" in {
removed commented code

2021-11-10 15:30 UTC, yasaracar approved these changes

2021-11-10 15:46 UTC, merged