Ecc 662
hmrc/xi-eori-common-component-frontend pull request #27
Opened 2021-12-03 09:09 UTC by NandanaRaghu

2021-12-06 13:08 UTC, yasaracar requested changes

2021-12-06 13:08 UTC, yasaracar commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/views/components/vat_details.scala.html
> +@getXiVatNumber = @{
Can we move these to the controller? It is not a good practice writing these kind of logic in the view. It is better when the views are as plain as possible

2021-12-07 08:48 UTC, NandanaRaghu commented on app/uk/gov/hmrc/xieoricommoncomponentfrontend/views/components/vat_details.scala.html
> +@getXiVatNumber = @{
Moved the logic to controller

2021-12-07 10:28 UTC, yasaracar approved these changes

2021-12-07 11:34 UTC, merged